restart-times: 0
use-conda: true
jobscript: "jobscript.sh"
cluster-config: "cluster.json"
jobname: "{rule}.{jobid}"
drmaa: " -P roslin_HighlanderLab -cwd -l h_vmem={cluster.mem} -l
h_rt={cluster.time} -l rl9=true -pe sharedmem {cluster.threads} -R y"
rerun-incomplete: true
rerun-triggers: [mtime, input]
local-cores: 99
keep-going: false